# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='公司全称')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('tel', models.CharField(blank=True, max_length=15, verbose_name='电话')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='产品名称')),
                ('price', models.FloatField(verbose_name='价格')),
                ('stock', models.IntegerField(max_length=5, verbose_name='库存')),
                ('create_date', models.DateField(verbose_name='生产日期')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Company')),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
    ]
